#!/usr/bin/env bun
// generate_init_script.ts
//
// Takes a selection.json payload on stdin (or as argument) and emits setup scripts
// that scaffold each selected catalog entry into a monorepo.
//
// Default output: setup.ts (runnable with `bun run setup.ts`).
// Optional outputs: --nu (setup.nu), --sh (setup.sh).
//
// Usage:
//   bun run scripts/generate_init_script.ts selection.json
//   cat selection.json | bun run scripts/generate_init_script.ts
//   bun run scripts/generate_init_script.ts selection.json --nu --sh
//   bun run scripts/generate_init_script.ts selection.json --output-dir=./my-project

import { readFile, writeFile, chmod } from "node:fs/promises";
import { parseArgs } from "node:util";
import { join } from "node:path";

type Action = "create-cloudflare" | "git-clone" | "fetch-docs" | "npm-package";

type Selection = {
  catalog_id: string;
  name: string;
  type: string;
  action: Action;
  target_dir: string;
  template_id?: string;
  url?: string;
  ref?: string;
  subpath?: string;
  package?: string;
};

type SelectionPayload = {
  project_name: string;
  project_slug?: string;
  monorepo_root?: string;
  selections: Selection[];
  user_notes?: string;
};

const { values: args, positionals } = parseArgs({
  args: process.argv.slice(2),
  options: {
    "output-dir": { type: "string", default: "." },
    "nu": { type: "boolean", default: false },
    "sh": { type: "boolean", default: false },
  },
  allowPositionals: true,
});

async function readSelection(): Promise<SelectionPayload> {
  if (positionals[0]) {
    const raw = await readFile(positionals[0], "utf8");
    return JSON.parse(raw);
  }
  // Read from stdin
  const chunks: Buffer[] = [];
  for await (const chunk of process.stdin) chunks.push(Buffer.from(chunk));
  const raw = Buffer.concat(chunks).toString("utf8");
  if (!raw.trim()) {
    throw new Error("No selection provided. Pass a file path or pipe JSON via stdin.");
  }
  return JSON.parse(raw);
}

function validate(sel: SelectionPayload): void {
  if (!sel.project_name) throw new Error("selection.json missing required field: project_name");
  if (!Array.isArray(sel.selections)) throw new Error("selection.json missing required field: selections");
  if (sel.selections.length === 0) throw new Error("selection.json has empty selections array");
  for (const [i, s] of sel.selections.entries()) {
    if (!s.action) throw new Error(`selections[${i}] missing action`);
    if (!s.target_dir) throw new Error(`selections[${i}] missing target_dir`);
    if (s.action === "create-cloudflare" && !s.template_id) throw new Error(`selections[${i}] action=create-cloudflare requires template_id`);
    if (s.action === "git-clone" && !s.url) throw new Error(`selections[${i}] action=git-clone requires url`);
    if (s.action === "fetch-docs" && !s.url) throw new Error(`selections[${i}] action=fetch-docs requires url`);
    if (s.action === "npm-package" && !s.package) throw new Error(`selections[${i}] action=npm-package requires package`);
  }
}

function renderTs(sel: SelectionPayload): string {
  const root = sel.monorepo_root || "./scaffolding";
  const selectionsJson = JSON.stringify(sel.selections, null, 2);

  return `#!/usr/bin/env -S bun run
// setup.ts - generated by cloudflare-compose
// Project: ${sel.project_name}
// Generated: ${new Date().toISOString()}
// Selection count: ${sel.selections.length}
//
// Usage: bun run setup.ts

import { mkdir, writeFile, appendFile, rename, readdir } from "node:fs/promises";
import { existsSync } from "node:fs";
import { spawn } from "node:child_process";
import { join, dirname } from "node:path";

const ROOT = ${JSON.stringify(root)};
const DOCS_ROOT = "docs/reference-architectures";
const LOG_PATH = \`\${ROOT}/.setup.log\`;

const SELECTIONS = ${selectionsJson} as const;

async function log(msg: string): Promise<void> {
  const line = \`\${new Date().toTimeString().slice(0, 8)}  \${msg}\`;
  console.log(line);
  try {
    await appendFile(LOG_PATH, line + "\\n");
  } catch {}
}

function run(cmd: string, args: string[], opts: { cwd?: string } = {}): Promise<number> {
  return new Promise((resolve, reject) => {
    const child = spawn(cmd, args, { cwd: opts.cwd, stdio: "inherit" });
    child.on("close", code => resolve(code ?? 1));
    child.on("error", reject);
  });
}

async function runStep(index: number, sel: typeof SELECTIONS[number]): Promise<void> {
  const label = \`[\${index + 1}/\${SELECTIONS.length}] \${sel.action}: \${sel.name}\`;
  await log(label);

  switch (sel.action) {
    case "create-cloudflare": {
      const code = await run("bun", [
        "create", "cloudflare@latest", sel.target_dir,
        "--", "--template=" + sel.template_id,
        "--no-deploy", "--no-git", "--no-open",
      ], { cwd: ROOT });
      if (code !== 0) await log(\`  WARN: create-cloudflare exited with code \${code}\`);
      break;
    }
    case "git-clone": {
      const ref = sel.ref || "main";
      const targetPath = \`\${ROOT}/\${sel.target_dir}\`;
      const code = await run("git", [
        "clone", "--depth=1", "--branch=" + ref, sel.url!, targetPath,
      ]);
      if (code !== 0) {
        await log(\`  WARN: git clone exited with code \${code}\`);
        return;
      }
      // If source has a subpath, lift it to the target root
      if (sel.subpath) {
        const subPath = \`\${targetPath}/\${sel.subpath}\`;
        if (existsSync(subPath)) {
          const entries = await readdir(subPath);
          for (const entry of entries) {
            await rename(\`\${subPath}/\${entry}\`, \`\${targetPath}/\${entry}\`);
          }
          await log(\`  Lifted contents of subpath \${sel.subpath} to target root\`);
        }
      }
      break;
    }
    case "fetch-docs": {
      const outPath = sel.target_dir;
      await mkdir(dirname(outPath), { recursive: true });
      try {
        const res = await fetch(sel.url!);
        if (!res.ok) throw new Error(\`HTTP \${res.status}\`);
        const html = await res.text();
        // Try pandoc if available, otherwise write raw HTML with a .html extension
        const hasPandoc = await run("pandoc", ["--version"]).then(c => c === 0).catch(() => false);
        if (hasPandoc) {
          await writeFile(outPath + ".tmp.html", html);
          await run("pandoc", ["-f", "html", "-t", "markdown", "-o", outPath, outPath + ".tmp.html"]);
          await run("rm", [outPath + ".tmp.html"]);
        } else {
          const htmlPath = outPath.replace(/\\.md$/, ".html");
          await writeFile(htmlPath, html);
          await log(\`  pandoc not found; wrote raw HTML to \${htmlPath}\`);
        }
      } catch (e) {
        await log(\`  ERROR: fetch-docs failed: \${e instanceof Error ? e.message : String(e)}\`);
      }
      break;
    }
    case "npm-package": {
      const targetPath = \`\${ROOT}/\${sel.target_dir}\`;
      await mkdir(targetPath, { recursive: true });
      await run("bun", ["init", "-y"], { cwd: targetPath });
      await run("bun", ["add", sel.package!], { cwd: targetPath });
      break;
    }
    default: {
      await log(\`  ERROR: unknown action: \${(sel as { action: string }).action}\`);
    }
  }
}

async function main(): Promise<void> {
  await mkdir(ROOT, { recursive: true });
  await mkdir(DOCS_ROOT, { recursive: true });
  await writeFile(LOG_PATH, \`# setup.ts log - started \${new Date().toISOString()}\\n\`);

  console.log(\`Scaffolding into: \${ROOT}\`);
  console.log(\`Selections: \${SELECTIONS.length}\`);
  console.log("");

  for (const [i, sel] of SELECTIONS.entries()) {
    try {
      await runStep(i, sel);
    } catch (e) {
      await log(\`  ERROR on step \${i + 1}: \${e instanceof Error ? e.message : String(e)}\`);
    }
  }

  console.log("");
  console.log(\`Scaffolding complete. Log: \${LOG_PATH}\`);
  console.log("Next: ask Claude to run analyze_scaffold.ts over the scaffolded tree.");
}

main().catch(e => {
  console.error(e);
  process.exit(1);
});
`;
}

function renderNu(sel: SelectionPayload): string {
  const root = sel.monorepo_root || "./scaffolding";
  const steps = sel.selections.map((s, i) => renderStepNu(s, i)).join("\n");

  return `#!/usr/bin/env -S nu --stdin

# setup.nu - generated by cloudflare-compose
# Project: ${sel.project_name}
# Generated: ${new Date().toISOString()}
# Selection count: ${sel.selections.length}

def main [] {
    let root = ${JSON.stringify(root)}
    let docs_root = "docs/reference-architectures"
    let log_path = $"($root)/.setup.log"

    mkdir $root
    mkdir $docs_root
    $"# setup.nu log - started (date now | format date '%Y-%m-%dT%H:%M:%S%z')" | save --force $log_path

    print $"Scaffolding into: ($root)"
${steps}
    print ""
    print $"Scaffolding complete. Log: ($log_path)"
    print "Next: ask Claude to run analyze_scaffold.ts over the scaffolded tree."
}

def log [msg: string, log_path: string] {
    let line = $"(date now | format date '%H:%M:%S')  ($msg)"
    print $line
    $"\\n($line)" | save --append $log_path
}
`;
}

function renderStepNu(sel: Selection, i: number): string {
  const idx = i + 1;
  switch (sel.action) {
    case "create-cloudflare":
      return `    log "[${idx}] create-cloudflare: ${sel.name} - template=${sel.template_id}" $log_path
    cd $root
    ^bun create cloudflare@latest ${sel.target_dir} -- --template=${sel.template_id} --no-deploy --no-git --no-open
    cd -`;
    case "git-clone": {
      const ref = sel.ref || "main";
      return `    log "[${idx}] git-clone: ${sel.name} - ${sel.url}@${ref}" $log_path
    ^git clone --depth=1 --branch=${ref} ${sel.url} $"($root)/${sel.target_dir}"`;
    }
    case "fetch-docs":
      return `    log "[${idx}] fetch-docs: ${sel.name} - ${sel.url}" $log_path
    mkdir (${JSON.stringify(sel.target_dir)} | path dirname)
    let html = (^curl -sSL ${sel.url})
    $html | save --force ${JSON.stringify(sel.target_dir)}`;
    case "npm-package":
      return `    log "[${idx}] npm-package: ${sel.name} - ${sel.package}" $log_path
    mkdir $"($root)/${sel.target_dir}"
    cd $"($root)/${sel.target_dir}"
    ^bun init -y
    ^bun add ${sel.package}
    cd -`;
    default:
      return `    log "[${idx}] unknown action" $log_path`;
  }
}

function renderSh(sel: SelectionPayload): string {
  const root = sel.monorepo_root || "./scaffolding";
  const steps = sel.selections.map((s, i) => renderStepSh(s, i)).join("\n\n");

  return `#!/usr/bin/env bash
# setup.sh - bash fallback generated by cloudflare-compose
# Project: ${sel.project_name}
# Generated: ${new Date().toISOString()}
set -euo pipefail

ROOT="${root}"
DOCS_ROOT="docs/reference-architectures"
LOG="$ROOT/.setup.log"

mkdir -p "$ROOT" "$DOCS_ROOT"
echo "# setup.sh log - started $(date -Iseconds)" > "$LOG"

log() { printf '%s  %s\\n' "$(date +%H:%M:%S)" "$1" | tee -a "$LOG"; }

echo "Scaffolding into: $ROOT"

${steps}

echo ''
echo "Scaffolding complete. Log: $LOG"
echo 'Next: ask Claude to run analyze_scaffold.ts over the scaffolded tree.'
`;
}

function renderStepSh(sel: Selection, i: number): string {
  const idx = i + 1;
  switch (sel.action) {
    case "create-cloudflare":
      return `log '[${idx}] create-cloudflare: ${sel.name}'
(cd "$ROOT" && bun create cloudflare@latest "${sel.target_dir}" -- --template="${sel.template_id}" --no-deploy --no-git --no-open)`;
    case "git-clone": {
      const ref = sel.ref || "main";
      return `log '[${idx}] git-clone: ${sel.name}'
git clone --depth=1 --branch="${ref}" "${sel.url}" "$ROOT/${sel.target_dir}"`;
    }
    case "fetch-docs":
      return `log '[${idx}] fetch-docs: ${sel.name}'
mkdir -p "$(dirname "${sel.target_dir}")"
curl -sSL "${sel.url}" -o "${sel.target_dir}"`;
    case "npm-package":
      return `log '[${idx}] npm-package: ${sel.name}'
mkdir -p "$ROOT/${sel.target_dir}"
(cd "$ROOT/${sel.target_dir}" && bun init -y && bun add "${sel.package}")`;
    default:
      return `log '[${idx}] unknown action'`;
  }
}

async function main(): Promise<void> {
  const selection = await readSelection();
  validate(selection);

  const outDir = args["output-dir"]!;

  // Always write setup.ts (default)
  const tsPath = join(outDir, "setup.ts");
  await writeFile(tsPath, renderTs(selection));
  await chmod(tsPath, 0o755);
  console.log(`Wrote ${tsPath}`);

  if (args.nu) {
    const nuPath = join(outDir, "setup.nu");
    await writeFile(nuPath, renderNu(selection));
    await chmod(nuPath, 0o755);
    console.log(`Wrote ${nuPath}`);
  }

  if (args.sh) {
    const shPath = join(outDir, "setup.sh");
    await writeFile(shPath, renderSh(selection));
    await chmod(shPath, 0o755);
    console.log(`Wrote ${shPath}`);
  }

  console.log(`\nRun: bun run ${tsPath}`);
}

main().catch(e => {
  console.error(e);
  process.exit(1);
});
